relativeURLs = true
languageCode = "en-us"
title = "Pedrito"
theme = "mytheme"
googleAnalytics = ""
publishDir = "docs"

DefaultContentLanguage = "es"

[languages]
  [languages.en]
    [[languages.en.menu.main]]
	  identifier = "about"
      name = "About"
      url = "/about/"
	[[languages.en.menu.main]]
	  identifier = "posts"
      name = "Posts"
      url = "/posts/"
  [languages.es]
    [[languages.es.menu.main]]
	  identifier = "nosotros"
      name = "Nosotros"
      url = "/nosotros/"
	[[languages.es.menu.main]]
	  identifier = "cositas"
      name = "Cositas"
      url = "/posts/"