relativeURLs = true
languageCode = "en-us"
title = "Pedrito"
theme = "mytheme"
googleAnalytics = ""
publishDir = "docs"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"